library(OlinkAnalyze)
library(dplyr)
library(ggplot2)
library(stringr)

#Import batches of NPX data generated by Olink NPX signature
data1 <- read_NPX(file.choose())
data2 <- read_NPX(file.choose())

#Merge different batches of data
npx1 <- data1 %>%
mutate(dataset = "data1")

npx2 <- data2 %>%
mutate(dataset = "data2")

npx_df <- bind_rows(npx1, npx2)

#Before normalization evaluation
npx_df %>%
mutate(Panel = gsub("Olink", "", Panel)) %>%
ggplot(aes(x = NPX, fill = dataset)) +
geom_density(alpha = 0.4) +
facet_grid(~Panel)+
set_plot_theme()+
ggtitle("Before briding normalization: NPX distribution")+
theme(axis.title.x = element_blank(),
aixs.title.y = element_blank(),
strip.text = element_text(size = 16),
legend.title = element_blank(),
legend.position = "top")

#Set briding samples
overlap_samples <- c("PAR202207197", "PAR202208265", "PAR202204023", "PAR202204027", "PAR202208275", "PAR202204021", "PAR202204019", "PAR202205059")

#Briding normalization
npx_br_data <- olink_normalization(df1 = npx1,
df2 = npx2,
overlapping_samples_df1 = overlap_samples,
df1_project_nr = 'data1',
df2_project_nr = 'data2',
reference_project = 'data1')

#Evaluation after normalization
npx_br_data %>%
mutate(Panel = gsub("Olink", "", Panel)) %>%
ggplot(aes(x = NPX, fill = dataset)) +
geom_density(alpha = 0.4) +
facet_grid(~Panel)+
set_plot_theme()+
ggtitle("After briding normalization: NPX distribution")+
theme(axis.title.x = element_blank(),
axis.title.y = element_blank(),
strip.text = element_text(size = 16),
legend.title = element_blank(),
legend.position = "top")

#Evaluation after normalization
npx_br_data %>%
mutate(Panel = gsub("Olink", "", Panel)) %>%
ggplot(aes(x = NPX, fill = dataset)) +
geom_density(alpha = 0.4) +
facet_grid(~Panel)+
set_plot_theme()+
ggtitle("After briding normalization: NPX distribution")+
theme(axis.title.x = element_blank(),
axis.title.y = element_blank(),
strip.text = element_text(size = 16),
legend.title = element_blank(),
legend.position = "top")

#Export bridging normalized data
write.csv(npx_br_data,file = "Bridge_Normalized_NPX_data.csv")